### ISSUE TITLE
Code review I

### ISSUE THREAD

**Issue by anitaschiller** [thomasmueller87/capstone-project#4]
Hi Thomas,
since you directly added the basic structure on the main branch, I will do the code review here 😉. 
Overall nice work, the structure looks good, just some remarks:
***
- Your `GlobalStyles` are in the components folder at the moment, please move it outside to the same level as your `App.jsx`
- Since your `GlobalStyles` don't include any JSX, please rename the file to `GlobalStyles.js`
- You could rename your `graphics` folder to `assets` - it's not wrong, but `assets` is much more used
- The content in your `server` folder doesn't seem to fit to the content in the `client` folder, I think it would be better to empty the server files

***
https://github.com/thomasmueller87/capstone-project/blob/970de2233810c192c8e06521d648feabdbfdccd3/client/src/App.jsx#L2
Unused code should be deleted! ;) 
***
https://github.com/thomasmueller87/capstone-project/blob/970de2233810c192c8e06521d648feabdbfdccd3/client/src/App.jsx#L12
`br` should not be used to generate space - pls add space via CSS
***
https://github.com/thomasmueller87/capstone-project/blob/970de2233810c192c8e06521d648feabdbfdccd3/client/src/components/Navbar.jsx#L6
Instead of the `divs`, a `nav` with a `ul` inside would semantically be better. Apart from that - why are there generally two navigations? One working and one dummy? 
***

**Comment by thomasmueller87** [comment]
Anita, thanks or that. Most issues solved!
Server needs to be ignored for now. Will add this to readme.md :)
